/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BannerFuncionallity: typeof import('./components/BannerFuncionallity.vue')['default']
    BannerLayoutSystem: typeof import('./components/BannerLayoutSystem.vue')['default']
    BussinessEvent: typeof import('./components/event-sale/BussinessEvent.vue')['default']
    CardsSkills: typeof import('./components/CardsSkills.vue')['default']
    ConferenceEvents: typeof import('./components/event-sale/ConferenceEvents.vue')['default']
    CreatedFacilityContainer: typeof import('./components/CreatedFacilityContainer.vue')['default']
    FooterBar: typeof import('./components/FooterBar.vue')['default']
    HighlightEvents: typeof import('./components/event-sale/HighlightEvents.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Networkingevents: typeof import('./components/event-sale/Networkingevents.vue')['default']
    OrganizationEvent: typeof import('./components/OrganizationEvent.vue')['default']
    PasswordField: typeof import('./components/PasswordField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchEvents: typeof import('./components/event-sale/SearchEvents.vue')['default']
    SeminarEvents: typeof import('./components/event-sale/SeminarEvents.vue')['default']
    WorkshopsEvent: typeof import('./components/event-sale/WorkshopsEvent.vue')['default']
  }
}
